name: YourPrefix
version: ${project.version}
main: net.poweredbyhate.yourprefix.YourPrefix
depend: [Vault]
authors: [LaxWasHere]
commands:
  yourprefix:
    aliases: [myprefix, yp, mp, yprefix, prefix]
